version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aicity-frontend
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: aicity-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment these lines when you have SSL certificates
      # - ./ssl/:/etc/nginx/ssl/
      # - ./ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
    depends_on:
      - frontend
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
