name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY')
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy Frontend to EC2
        run: |
          ssh ec2 'cd /home/ec2-user/apps/frontend/aicity-front && \
          git pull origin main && \
          # Force remove the container if it exists
          docker rm -f aicity-front || echo "No container to remove" && \
          # Remove old images to free up space
          docker image prune -f && \
          # Build and run new container
          docker build -t aicity-front . && \
          docker run --name aicity-front --network aicity-network -p 3000:3000 --env-file .env.local -d aicity-front'
